### ISSUE TITLE
example - visual indicator for composite field

### ISSUE THREAD

**Issue by sarbbottam** [sarbbottam/accessible-dropdown#10]
Currently there is a combined visual indicator for the composite field.

![focus-indicator](https://cloud.githubusercontent.com/assets/949380/14654926/d518c836-0634-11e6-81dc-74f90d5b1be2.gif)

Though blinking cursor could be an identifier but it is not intuitive, it is better to highlight the dropdown uniquely when focused.

Reference: https://twitter.com/thierrykoblentz/status/722523899745816576

**Comment by thierryk** [comment]
Both "fields" should get a visual indicator. When you tab back from that "Mobile Number" field, the "dropdown" should get some styling to indicate it is actionable and that's where the cursor is.
As I mentioned in my tweet, the issue is mainly when you tab **back** from the "Mobile Number" field.

**Comment by sarbbottam** [comment]
@thierryk does it look reasonable?
![focus-indicator](https://cloud.githubusercontent.com/assets/949380/14655463/4d823724-0637-11e6-8c03-3ae1e12379c9.gif)

**Comment by thierryk** [comment]
Much better.
